packages:
- '.'
- location: './taffybar'
  extra-dep: true
- location:
    git: https://github.com/willdonnelly/dyre
    commit: 11412752b483135e0c151ab90be17b217f837c4b
  extra-dep: true
extra-deps:
- gio-0.13.4.1
- gtk-0.14.7
- gtk-traymanager-0.1.6
- rate-limit-1.1.1
- time-1.6.0.1
- time-units-1.0.0
- xml-helpers-1.0.0
resolver: lts-10.2
